<?php

$this->headScript()->appendFile($this->basePath('/js/koszyk.js'), 'text/javascript', ['defer' => true]);
$form->setAttribute('action', $this->url('nieruchomosci/koszyk', []))

?>

<?= $this->form()->openTag($form) ?>

<h2 class="my-3">Koszyk uzytkownika</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th><?= $form->get('typ_oferty')->getLabel() ?></th>
            <th><?= $form->get('typ_nieruchomosci')->getLabel() ?></th>
            <th><?= $form->get('numer')->getLabel() ?></th>
            <th></th>
        </tr>
        <tr class="szukaj">
            <th></th>
            <th><?= $this->formElement($form->get('typ_oferty')) ?></th>
            <th><?= $this->formElement($form->get('typ_nieruchomosci')) ?></th>
            <th><?= $this->formElement($form->get('numer')) ?></th>
            <th><?= $this->formSubmit($form->get('szukaj')) ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($oferty as $o): ?>
            <tr>
                <td><?= $o->id ?></td>
                <td><?= $o->typ_oferty ?></td>
                <td><?= $o->typ_nieruchomosci ?></td>
                <td><?= $o->numer ?></td>
                <td><?= $o->powierzchnia ?></td>
                <td><?= $o->cena ?></td>
                <td class="text-nowrap">
                    <a
                            href="<?= $this->url('nieruchomosci/oferty', ['action' => 'szczegoly', 'id' => $o->id]) ?>"
                            title="szczegóły"
                    ><i class="fas fa-folder-open"></i></a>
                    &nbsp;
                    <a
                            href="<?= $this->url('nieruchomosci/koszyk', ['action' => 'usun', 'id' => $o->id]) ?>"
                            title="usun z koszyka"
                            class="aUsunZKoszyka"
                    ><i class="fas fa-cart-plus"></i></a>
                    &nbsp;
                    <a
                            href="<?= $this->url('nieruchomosci/oferty', ['action' => 'drukuj', 'id' => $o->id]) ?>"
                            title="drukuj"
                    ><i class="fas fa-print"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
</table>

<?= $this->paginationControl(
    $oferty, 
    'sliding', 
    ['partial/paginator.phtml', 'Nieruchomosci'], 
    ['route' => 'nieruchomosci/koszyk', 'parametry' => $parametry]
)
?>

<?= $this->form()->closeTag($form); ?>
<strong>Drukuj wszystko</strong>
<a
    href="<?= $this->url('nieruchomosci/oferty', ['action' => 'drukujWszystko']) ?>"
    title="drukuj"
>
<i class="fas fa-print"></i>
</a>